// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cogzohtwkdqpvoxqlkta.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNvZ3pvaHR3a2RxcHZveHFsa3RhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NjM4OTEsImV4cCI6MjA3MDEzOTg5MX0.GjspM0TYE8riZgXIKjHjPUXIsnJCUqBIEqIenO8lzLQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});